#pragma once
// What the pinned llama.cpp build can be asked to run, stated honestly (docs/backends/llama-local.md, ADR 0408).
//
// Three tiers of knowledge about a GGUF `general.architecture`:
//   kExercised - ClusterLM has a test that loads a tiny random-weight model of this architecture with the pinned
//                llama.cpp and checks the backend's decode against llama.cpp's own (tests/backends_llama/
//                test_llama_architectures.cpp). Mechanics evidence on a CPU fixture only: not a statement about any
//                real checkpoint, quality or GPU behaviour.
//   kKnown     - the pinned llama.cpp names this architecture; ClusterLM has never run it. Experimental at best.
//   kUnknown   - the pinned llama.cpp does not name it. Loading cannot succeed; report Unsupported up front.
#include <filesystem>
#include <string_view>
#include <vector>

#include "clusterlm/common/status.hpp"

namespace clusterlm::backends {

enum class LlamaArchSupport { kExercised, kKnown, kUnknown };

// Every architecture string the pinned llama.cpp can name (sorted; generated by scripts/gen_llama_arch_table.py).
const std::vector<std::string_view>& llama_pinned_architectures();
// The subset ClusterLM exercises in CI (sorted). Always a subset of llama_pinned_architectures().
const std::vector<std::string_view>& llama_exercised_architectures();

LlamaArchSupport llama_architecture_support(std::string_view architecture);

// Cheap loadability probe: asks the pinned llama.cpp to parse the GGUF's hyper-parameters and vocabulary only
// (vocab_only), without reading tensor data or allocating weights. Fails for files the pinned build cannot interpret
// (unknown architecture, missing or inconsistent keys). Success is necessary, not sufficient: tensors are not checked.
Status probe_llama_hparams(const std::filesystem::path& gguf);

// The shipped declarative descriptor of this backend (backend-capability-v1 JSON), embedded at build time from
// runtime/backends/llama/descriptor/llama-local.descriptor.json. Embedded, so a missing file can never change what
// is advertised. Parsing and the BackendRegistry belong to the descriptor type owned by workstream A (CMR-0001).
std::string_view llama_local_descriptor_json();

}  // namespace clusterlm::backends
