#!/usr/bin/env python3
"""Regenerate runtime/backends/llama/src/llama_arch_table.inc from the pinned llama.cpp checkout.

The table lists every GGUF `general.architecture` string the pinned llama.cpp can name (LLM_ARCH_NAMES in
src/llama-arch.cpp), minus the two entries that are not model architectures ("clip", "(unknown)"). It is what lets the
backend tell "the pinned build has never heard of this architecture" (Unsupported) from "the pinned build knows it but
ClusterLM has not exercised it" (Experimental). Knowing a name proves nothing about execution quality.

  python3 scripts/gen_llama_arch_table.py            # rewrite the .inc
  python3 scripts/gen_llama_arch_table.py --check    # exit 1 when the .inc differs from the checkout (used by CI)

Stdlib only; needs `python3 scripts/fetch_upstream.py llama.cpp` first.
"""
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SRC = ROOT / "third_party" / "upstream" / "llama.cpp" / "src" / "llama-arch.cpp"
OUT = ROOT / "runtime" / "backends" / "llama" / "src" / "llama_arch_table.inc"
SKIP = {"clip", "(unknown)"}


def names():
    text = SRC.read_text(encoding="utf-8")
    m = re.search(r"LLM_ARCH_NAMES\s*=\s*\{(.*?)\n\};", text, re.S)
    if not m:
        sys.exit("LLM_ARCH_NAMES not found in " + str(SRC))
    found = re.findall(r'\{\s*LLM_ARCH_[A-Z0-9_]+\s*,\s*"([^"]+)"\s*\}', m.group(1))
    return sorted(set(found) - SKIP)


def render(pin):
    body = "".join(f'    "{n}",\n' for n in names())
    return (f"// Generated by scripts/gen_llama_arch_table.py from llama.cpp {pin}. Do not edit by hand.\n"
            f"// Every general.architecture string the pinned llama.cpp can name, sorted.\n{body}")


def main():
    if not SRC.exists():
        sys.exit("missing " + str(SRC) + " (run: python3 scripts/fetch_upstream.py llama.cpp)")
    pins = json.loads((ROOT / "third_party" / "upstream.json").read_text())
    text = render(pins["pins"]["llama.cpp"]["commit"])
    if "--check" in sys.argv:
        if not OUT.exists() or OUT.read_text() != text:
            print("llama_arch_table.inc is stale; run scripts/gen_llama_arch_table.py")
            return 1
        print("llama_arch_table.inc is current (%d architectures)" % len(names()))
        return 0
    OUT.write_text(text)
    print("wrote %s (%d architectures)" % (OUT.relative_to(ROOT), len(names())))
    return 0


if __name__ == "__main__":
    sys.exit(main())
