#!/usr/bin/env python3
"""Generates orchestrator/father-service/src/unicode_tables.cpp: a compact code point -> {letter, mark, number,
other} range table for the Father GGUF BPE tokenizer's pre-tokenizer (\\p{L}, \\p{M}, \\p{N}).

The table is derived from Python's `unicodedata` (general category; same mapping llama.cpp's own
scripts/gen-unicode-data.py uses: L* -> letter, M* -> mark, N* -> number, everything else -> other).
Unassigned code points are "other". Whitespace is NOT in the table (it is the fixed Unicode White_Space set,
spelled out in the C++ source).

Each entry packs (first_code_point << 2) | class; an entry applies until the next entry's first code point.

    python3 scripts/gen_unicode_tables.py            # rewrites the committed file
    python3 scripts/gen_unicode_tables.py --stdout   # print instead

The committed file records the unicodedata version it was generated from. A newer Python may move a few
recently assigned code points between classes; regenerate deliberately and re-run the vocab tests.
"""
import sys
import unicodedata
from pathlib import Path

MAX_CP = 0x110000
OTHER, LETTER, MARK, NUMBER = 0, 1, 2, 3


def classify(cp: int) -> int:
    cat = unicodedata.category(chr(cp))
    if cat[0] == "L":
        return LETTER
    if cat[0] == "M":
        return MARK
    if cat[0] == "N":
        return NUMBER
    return OTHER


def build() -> list:
    entries = []
    prev = None
    for cp in range(MAX_CP):
        c = classify(cp)
        if c != prev:
            entries.append((cp << 2) | c)
            prev = c
    return entries


def render(entries: list) -> str:
    lines = []
    lines.append("// GENERATED by scripts/gen_unicode_tables.py - do not edit by hand.")
    lines.append("// Source: Python unicodedata, Unicode %s. Classes: 0 other, 1 letter (L*), 2 mark (M*), 3 number (N*)." %
                 unicodedata.unidata_version)
    lines.append("// Entry = (first code point << 2) | class; it applies until the next entry's first code point.")
    lines.append('#include "unicode_tables.hpp"')
    lines.append("")
    lines.append("namespace clusterlm::father::unicode {")
    lines.append("")
    lines.append('const char* const kUnicodeVersion = "%s";' % unicodedata.unidata_version)
    lines.append("")
    lines.append("const std::uint32_t kClassRanges[] = {")
    row = []
    for e in entries:
        row.append("0x%x" % e)
        if len(row) == 8:
            lines.append("    " + ", ".join(row) + ",")
            row = []
    if row:
        lines.append("    " + ", ".join(row) + ",")
    lines.append("};")
    lines.append("")
    lines.append("const std::size_t kClassRangeCount = %d;" % len(entries))
    lines.append("")
    lines.append("}  // namespace clusterlm::father::unicode")
    lines.append("")
    return "\n".join(lines)


def main() -> int:
    text = render(build())
    if "--stdout" in sys.argv:
        sys.stdout.write(text)
        return 0
    out = Path(__file__).resolve().parent.parent / "orchestrator" / "father-service" / "src" / "unicode_tables.cpp"
    out.write_text(text)
    print("wrote %s (%d bytes)" % (out, len(text)))
    return 0


if __name__ == "__main__":
    sys.exit(main())
