#!/usr/bin/env python3
"""Generate HARDWARE-QUALIFICATION.md from bench/qualification/experiments.json.

The JSON registry is the single source of truth (ClusterLM Bench reads it too). Run with --check in CI to
fail when the Markdown is stale.
"""
import argparse
import json
import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
REGISTRY = ROOT / "bench" / "qualification" / "experiments.json"
OUTPUT = ROOT / "HARDWARE-QUALIFICATION.md"

HEADER = """# ClusterLM hardware qualification

<!-- Generated by scripts/gen_qualification_md.py from bench/qualification/experiments.json. Do not edit by hand. -->

Every experiment below requires the physical machines. None of them can be satisfied by the synthetic
profiles in `fixtures/profiles/`, by localhost clusters, or by the simulated network presets — those exist to
exercise the software, not to measure the hardware. Until an experiment has a recorded result produced on the
real machines, every quantity it decides remains **pending qualification**, and no tier may be marked
`Qualified`.

Results are emitted by `clusterlm-bench` in the schema `bench/schema/benchmark-result.schema.json`. A result
names the experiment ID, the exact build, model hashes, machine profiles and its provenance (`Measured`).

## Not claimed until these experiments pass

Fast / Strong / Ultra tok/s · 20+ tok/s Ultra · optimal layer boundaries · optimal expert residency ·
CPU/GPU miss crossover · MTP acceptance and net benefit · safe VRAM margins · laptop sustained thermal
performance · real network latency/bandwidth · provisioning speed · release latency under real drivers ·
Windows pinned-memory behaviour.

## Summary

| ID | Experiment | Machines | Status |
|---|---|---|---|
"""


def machine_short(m: str) -> str:
    return m.split(" (")[0]


def render(reg: dict) -> str:
    out = [HEADER]
    for e in reg["experiments"]:
        machines = ", ".join(machine_short(m) for m in e["machines"])
        out.append(f"| [{e['id']}](#{e['id'].lower()}) | {e['title']} | {machines} | {e['status']} |\n")
    out.append("\n## Experiments\n")
    for e in reg["experiments"]:
        out.append(f"\n### {e['id']}\n\n**{e['title']}** — status: `{e['status']}`\n\n")
        out.append(f"- **Purpose:** {e['purpose']}\n")
        out.append(f"- **Command:** `{e['command']}`\n")
        out.append("- **Machines:** " + "; ".join(e["machines"]) + "\n")
        out.append(f"- **Model:** {e['model']}\n")
        out.append("- **Measurements:**\n")
        for m in e["measurements"]:
            out.append(f"  - {m}\n")
        metrics = ", ".join(f"`{m}`" for m in e["output"]["metrics"])
        out.append(f"- **Output:** `{e['output']['schema']}` with `experiment = \"{e['id']}\"`; metrics {metrics}\n")
        out.append(f"- **Decision affected:** {e['decision_affected']}\n")
        if "acceptance" in e:
            out.append(f"- **Acceptance:** {e['acceptance']}\n")
    return "".join(out)


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true", help="fail if the Markdown is out of date")
    args = ap.parse_args()
    reg = json.loads(REGISTRY.read_text(encoding="utf-8"))
    ids = [e["id"] for e in reg["experiments"]]
    if len(ids) != len(set(ids)):
        print("duplicate experiment IDs", file=sys.stderr)
        return 1
    text = render(reg)
    if args.check:
        if not OUTPUT.exists() or OUTPUT.read_text(encoding="utf-8") != text:
            print(f"{OUTPUT.name} is stale; run scripts/gen_qualification_md.py", file=sys.stderr)
            return 1
        return 0
    OUTPUT.write_text(text, encoding="utf-8", newline="\n")
    return 0


if __name__ == "__main__":
    sys.exit(main())
