# clusterlm_embed_text(<out_cpp_var> <source_file> <namespace> <function>)
#
# Generates a .cpp that defines `std::string_view <namespace>::<function>()` returning the exact bytes of
# <source_file>, embedded as a byte array (no string-literal length limit, identical on MSVC and GCC/Clang). The
# source is a configure dependency, so editing it regenerates the file. Used to embed backend descriptors so that a
# missing file at run time can never change which backend is advertised (backend-capability-v1 section 6).
function(clusterlm_embed_text out_var source ns func)
  get_filename_component(_name "${source}" NAME_WE)
  set(_out "${CMAKE_CURRENT_BINARY_DIR}/embedded_${_name}.cpp")
  set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS "${source}")
  file(READ "${source}" _hex HEX)
  string(LENGTH "${_hex}" _hexlen)
  math(EXPR _n "${_hexlen} / 2")
  string(REGEX REPLACE "([0-9a-f][0-9a-f])" "0x\\1," _bytes "${_hex}")
  file(WRITE "${_out}.tmp"
"// Generated by cmake/ClusterLMEmbed.cmake from ${source}. Do not edit.
#include <string_view>
namespace ${ns} {
namespace {
constexpr unsigned char kBytes[] = {${_bytes}0x00};
}
std::string_view ${func}() { return std::string_view(reinterpret_cast<const char*>(kBytes), ${_n}); }
}  // namespace ${ns}
")
  file(COPY_FILE "${_out}.tmp" "${_out}" ONLY_IF_DIFFERENT)
  file(REMOVE "${_out}.tmp")
  set(${out_var} "${_out}" PARENT_SCOPE)
endfunction()
